TRUNCATE TABLE "Property";
ALTER TABLE "Property" ADD COLUMN "userId" INTEGER NOT NULL;
ALTER TABLE "Property" ADD CONSTRAINT "Property_userId_fkey" 
  FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
